apiVersion: v1
data:
  mapRoles: |
    - rolearn: arn:aws:iam::008616580268:role/eksctl-roboshop-dev-nodegroup-robo-NodeInstanceRole-smCFU4aV2OaY
      groups:
      - system:bootstrappers
      - system:nodes
      username: system:node:{{EC2PrivateDNSName}}
  mapUsers: |
    - groups:
      - roboshop-trainee
      userarn: arn:aws:iam::008616580268:user/praveens
      username: praveens
    - groups:
      - roboshop-admin
      userarn: arn:aws:iam::008616580268:user/Ramesh
      username: Ramesh
    - groups:
      - roboshop-trainee
      userarn: arn:aws:iam::008616580268:user/jhon
      username: jhon
    - groups:
      - roboshop-trainee
      userarn: arn:aws:iam::008616580268:user/robert
      username: robert
kind: ConfigMap
metadata:
  creationTimestamp: "2026-06-16T07:10:48Z"
  name: aws-auth
  namespace: kube-system
  uid: 41b2d241-b60b-48be-b01e-1455b56cb045
